### PR TITLE
Set Network Timeout correctly

### PR DESCRIPTION
**Pull request by sp-gupta**
Details here: https://confluent.slack.com/archives/C04JZM847QR/p1675767317369199?thread_ts=1675742451.437759&cid=C04JZM847QR

### CODE REVIEW

**Comment by anupamaggarwal** [comment]
Thanks @sp-gupta  for the PR....

Couple of comments/nits ... I will let @ManasjyotiSharma  chime in also..

1. Should we move the logic of setter method to the build method (that seems like a more natural fit)  (the properties passed in can just be stored in some internal field) . Seems like it should be safe to do so (This might upset testSetSSLProperties but that test seems a bit strange to me, maybe we can assert on some getter method of SnowflakeConnectionService instead)  

`this.url = new SnowflakeURL(conf.get(Utils.SF_URL));
      this.prop = InternalUtils.createProperties(conf, this.url.sslEnabled(), this.networkTimeOut);
      this.kafkaProvider =
          SnowflakeSinkConnectorConfig.KafkaProvider.of(conf.get(PROVIDER_CONFIG)).name();
      // TODO: Ideally only one property is required, but because we dont pass it around in JDBC and
      // snowpipe SDK,
      //  it is better if we have two properties decoupled
      // Right now, proxy parameters are picked from jvm system properties, in future they need to
      // be decoupled
      this.proxyProperties = InternalUtils.generateProxyParametersIfRequired(conf);
      this.connectorName = conf.get(Utils.NAME);
  `
2 . Add a UT for testing the network timeout ? (In my local testing the  dns lookup for URL this connector was using was failing, so I was curious why the connector took so much time in the connect method of SnowFlakeDriver.  This UT will also help validate the fix before deploying on mothership

wdyt?

**Comment by ManasjyotiSharma** [comment]
Thanks @anupamaggarwal for your feedback; I agree on those points! A Builder should not depend on order of method invocation and infact Tushar raised a similar point to which I replied [here](https://confluent.slack.com/archives/C04JZM847QR/p1675778586774989?thread_ts=1675742451.437759&cid=C04JZM847QR). Coming to current issue; the 2 suggestions that you are making seems low hangning and I'd leave it to @sp-gupta to evaluate if he can incorporate the same into this PR due to following:
1. For current issue mitigation itself is "code fix and deployment" and that'd fall under on-call responsibility.
2. Refactoring the code to clean it and for better maintenability would fall on the SME.
3. Last but not the least - how is this PR going to be tested? IIRC we don't have valid SF account as of today to run the system tests (CC: @kapilchhajer) so any non-trivial change would be difficult to commit confidently. 

Noting above points I am actually ok to immediately mitigate the issue with the call swap change and definitely file a follow up AI for the SME to take care of the clean up and proper testing part.

**Review by ManasjyotiSharma — APPROVED** [review]
@sp-gupta  LGTM (please see this [comment](https://github.com/confluentinc/snowflake-kafka-connector/pull/32#issuecomment-1422239324)). Can you please file and link the AI into the RCCA to make the Builder order independent?

**Comment by ManasjyotiSharma** [comment]
@sp-gupta please raise a new PR against the version branch by looking at the current version being deployed in cc-docker-connect. Also while cutting a release make sure to select the stage option in the jenkins job so that an internal rc build version is generated for the connector.

**Review by kapilchhajer — APPROVED** [review]
LGTM.

@ManasjyotiSharma,
point no 2 - did we create any work item to fix it? if yes then you can assign it to me. 
point no 3 -  we got new account cred recently. @akanimesh7 will update the same in the KV.

**Pull request merged**
