### PR TITLE
Bump the snowflake-ingest-sdk with the hotfix to remove deadlock in poll

### PR DESCRIPTION
**Pull request by ddasarathan**

### CODE REVIEW

**Comment by ddasarathan** [comment]
https://confluent.jfrog.io/ui/native/maven-snapshots/net/snowflake/snowflake-ingest-sdk/0.10.3-hotfix1/

https://github.com/confluentinc/snowflake-ingest-java/tree/v0.10.3-hotfix1

**Comment by ddasarathan** [comment]
This bump basically adds the following code
```        CloseableHttpResponse response = this.httpClient.execute(httpPostForIngestFile);
        Throwable var7 = null;

        IngestResponse var8;
        try {
            LOGGER.info("Attempting to unmarshall insert response - {}", response);
            var8 = ServiceResponseHandler.unmarshallIngestResponse(response);
        } catch (Throwable var17) {
            var7 = var17;
            throw var17;
        } finally {
            if (response != null) {
                if (var7 != null) {
                    try {
                        response.close();
                    } catch (Throwable var16) {
                        var7.addSuppressed(var16);
                    }
                } else {
                    response.close();
                }
            }

        }

        return var8;
```

**Comment by ddasarathan** [comment]
Changes that got pulled https://github.com/confluentinc/snowflake-ingest-java/compare/v0.10.3...confluentinc:hotfix-0.10.x?expand=1

**Review by gharris1727 — APPROVED** [review]

**Comment by ddasarathan** [comment]
Thanks @greghensley

**Pull request merged**
